### ISSUE TITLE
Cannot use shortcodes on Trait Description

### ISSUE THREAD

**Issue by godimarcovr** [Skyl3lazer/giffyglyph-monster-maker-continued#13]
Hello, thanks for reviving this Foundry Module.
I'm currently using v0.3 (as my monsters are on GMMv2), I'm currently in the process of transfering my monsters to Foundry and so far it's working well.
I have an issue when editing a Trait Description with shortcodes. They are not interpreted and are left with the raw text (e.g. if I write "you deal [level] extra damage" it's not converted to "you deal 2 extra damage" with a lvl 2 monster). I assume it's a bug since the question mark on the top right mentions shortcodes.
They work without issues when I'm setting the attack bonus or damage from attacks.
I'm using Foundry v10.291 and DnD5e 2.2.1

Thank you so much for adopting this module!

**Comment by Skyl3lazer** [comment]
Yep, this is a known issue, but I missed putting it in the dev log. I need to find a clean way to do shortcodes without interfering with things like @condition[name] or @spell[name] tags. I'll tag this issue whenever I fix it.

**Comment by godimarcovr** [comment]
Thank you for your reply.
I have no idea of the code behind a Foundry module, so forgive me if I say something stupid. I work with Python and if I had to solve it with it, I would use a regular expression such as this
pattern1 = r'\[.*?\]'
to find all the matches with square brackets. Then I would do a second regex to match cases such as @spell[name] such as
pattern2 = r'@\w+\[.*?\]'
and then I would get all matches with pattern1 excluding those who overlap with the matches of pattern2.

It's probably more complex than this simple solution, but I hope it can be a good starting point for an idea to solve it in a clean way.
In any case, good job so far, I have been waiting a long time to use GMM monsters on foundry without having to make stuff in the Vault and manually copying it into Foundry

**Comment by Skyl3lazer** [comment]
You're not far off, it's almost certainly a regex fix. 

The complicating factor is the order of injection of the GGMM module's shortcodes - I need to make sure that I'm doing my replacements at the right "time", so that I don't throw unnecessary errors (i.e. reading a "shortcode" that isn't meant for GGMM), or fail to throw them when they are necessary (i.e. they entered a GGMM shortcode incorrectly). The existing shortcoder logic is also very straightforward and doesn't accept a lot of nuance in tags, so it partly needs a rewrite.

Thank you for the interest!

https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/blob/master/scripts/classes/Shortcoder.js

**Comment by Skyl3lazer** [comment]
So, I think some of this was already happening correctly on the backend but not displayed. Change is available in dev 11.0.1, give it a shot. 551aa41

**Comment by Skyl3lazer** [comment]
Fixed with 0.11

**Comment by godimarcovr** [comment]
> So, I think some of this was already happening correctly on the backend but not displayed. Change is available in dev 11.0.1, give it a shot. [551aa41](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/commit/551aa41f6677dcea3f451f8233b6f13c7a662ae4)

Thanks! I'm currently on GMMv2, has that also been updated?

**Comment by Skyl3lazer** [comment]
If you want to try doing a PR for it you're welcome to, but I am not putting more work on to the V2 branch - as stated in the readme, it's only really for data recovery of old games. You should look at upgrading to v3, it's an improvement!

**Comment by godimarcovr** [comment]
Got it, makes sense! I have some material still on v2, but I'm looking forward to move to v3 once I finish the current arc in my campaign.
