### ISSUE TITLE
Adding an action adds it into the trait section

### ISSUE THREAD

**Issue by noncasus** [Skyl3lazer/giffyglyph-monster-maker-continued#14]
Foundry v11.306
Latest libwrapper and GMMC

Used Find the Culprit to see if it was some other module conflict but nope.

![image](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/6765904/0ff29068-6672-454e-8a1b-93d98b106c9b)

**Comment by Skyl3lazer** [comment]
This is a known issue when adding an action to the 'global' scalar monster. For some reason when doing so, the feature is always set as a 'trait' by default. If you add it to the token actor it adds correctly, though that's less useful.

 You can manually change the type to an 'action' and it will sort correctly and work as expected.

**Comment by Skyl3lazer** [comment]
Fixed with 76d5cd921e9ffafc6d39fc0be368cb47d877995e
