### ISSUE TITLE
Actions description inline on monster sheet?

### ISSUE THREAD

**Issue by jared-sheets** [Skyl3lazer/giffyglyph-monster-maker-continued#16]
First, bless you for maintaining this project. This massively streamlines how I run DnD 5E on Foundry.

I wanted to confirm if the following format is still supported in the latest Monster Maker Continued version. Here's a screenshot of the module that I've seen that has the monster's traits and actions names and descriptions visible on the sheet: [https://imgur.com/a/VgUt33A](https://imgur.com/a/VgUt33A)

I can only get the monster's traits and action names to appear with no descriptions visible, like this: [https://imgur.com/a/gkHjotW](https://imgur.com/a/gkHjotW)

Is the format still supported where I can view the descriptions inline on the monster sheet? If so, can you direct me to where that option is?

My setup is:

Foundry V10.291
DnD5e V2.2.2
Giffyglyph Monster Make Continued V0.11.0.2
libWrapper 1.12.12.0

**Comment by Skyl3lazer** [comment]
You know, that's never worked since I updated it. I thought I remembered it
doing that in the foundry 0.8 version but never had confirmation until now.

Added to next release roadmap.

**Comment by Skyl3lazer** [comment]
Fixed in v0.12, thank you for the report and compliment :)
