### ISSUE TITLE
Cannot remove swarm size property after swarm size property has been set.

### ISSUE THREAD

**Issue by josephcyang4459** [Skyl3lazer/giffyglyph-monster-maker-continued#18]
Hello. I am new when it comes to creating issues on GitHub. I will try to be as concise as possible.

Recreation of issue.
1. Click "Create a Scaling Monster"
2. Open "New Scaling Monster" Actor
3. Click on description of monster (should be "Medium humanoid, unaligned" for new scaling monsters)
4. Change Swarm Size from empty to anything else
5. Attempt to remove swarm size.

I am able to change the swarm size to different sizes, but attempting to remove the swarm size does not work.
Below, I have put a short video displaying the issue:

https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/65678477/e5747104-3d72-4652-b166-dd88f1963175

**Comment by Skyl3lazer** [comment]
Fixed with a9706a26d1202cf8b9479451f9158f15866174b9 on dev
