### ISSUE TITLE
[Feature Request] Adding a shortcode for the monster's name

### ISSUE THREAD

**Issue by josephcyang4459** [Skyl3lazer/giffyglyph-monster-maker-continued#22]
I would like for a shortcode to be created that references the name of the monster. Main purpose would be to make it easier to reuse scaling actions on multiple monsters without having to change the description every time.

"The [name] attacks with its venomous fangs." ---> "The Huge Spider attacks with its venomous fangs"

**Comment by Skyl3lazer** [comment]
This is a good idea, and should be easy to implement I think. I'll add it to the 1.0 milestone.
