### ISSUE TITLE
Ammunition Incompatability

### ISSUE THREAD

**Issue by Albertmonkey9** [Skyl3lazer/giffyglyph-monster-maker-continued#24]
Consumable items cannot be utilized by scaling attacks. 

Notably, only the 'item uses' field under the "activation cost" tab seems to work, which is great for most purposes. 

However, consuming ammunition from a scaling monster's inventory seems unsupported for scaling actions.

**Comment by Skyl3lazer** [comment]
In general scaling abilities are meant to have uses of their own rather than consuming ammunition - those fields are legacy from v2. That said if they're there I should make them work, so I'll put this in as a bug that needs fixing at some point.

**Comment by Skyl3lazer** [comment]
Fixed on dev with 8fcb297!
