### ISSUE TITLE
Rarity Support

### ISSUE THREAD

**Issue by Skyl3lazer** [Skyl3lazer/giffyglyph-monster-maker-continued#34]
Add the ability for Scalar Abilities to have a Rarity. Rarity should adjust some UI elements to differentiate between them.

**Comment by CatbotTsumi** [comment]
Bringing some ideas for consideration...
- Perhaps colors things green, dark yellow, and dark red like in the pdf?
- Perhaps it would set a default image based on the rarity (color) and the icon based on it being a trait/action/paragon power/etc like the pdf does.
- Maybe it would be nice to calculate EP as well based on rarity and options, though i can imagine that's more complicated than i realize.

**Comment by Skyl3lazer** [comment]
Added on dev
