### ISSUE TITLE
Actions (and similar lists) dont update UI immediately when adding/removing actions

### ISSUE THREAD

**Issue by CatbotTsumi** [Skyl3lazer/giffyglyph-monster-maker-continued#36]
I made a video to demonstrate the issue.
[Video](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/63572588/02c45dda-7ed3-4bf6-b5cf-ded91441943b)

**Comment by Skyl3lazer** [comment]
This appears to be an issue with those buttons in the side panel specifically. The add and delete buttons in the main window work as expected.

**Comment by CatbotTsumi** [comment]
Hmmm i just tried, it doesnt on my end.

https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/63572588/8e56f9e4-6eeb-4b6b-a4ef-7d740185e5aa

**Comment by CatbotTsumi** [comment]
This time with console

https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/63572588/6ffcd32f-f407-4a1a-b091-e814b05f25c6

**Comment by Skyl3lazer** [comment]
Fixed on dev 1af0aa1
