### ISSUE TITLE
Categorize sidebar sections

### ISSUE THREAD

**Issue by CatbotTsumi** [Skyl3lazer/giffyglyph-monster-maker-continued#38]
Most of the sidebar sections are organized alphabetically, it would make for a much more pleasant monster making experience to have them sectioned by Details, Offense, Defense, Abilities and Features. (just like your webapp)
I don't think we specifically need a header text or collapsibles, as long as they're in an order that flows better and probably separated (just like how Description and Combat are separated)

![image](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/63572588/39716178-dc8d-41d0-ac3b-4140ae15ecf7)

**Comment by Skyl3lazer** [comment]
Added to 1.1 milestone

**Comment by Skyl3lazer** [comment]
Completed in 292ae11

**Comment by Skyl3lazer** [comment]
If people have suggestions/opinions on the sorting for these after seeing what I've changed, feel free to comment.

The vague idea now for the categories: Basic, Scaling Abilities, General Features, Overrides, Flavor, "Loot", Display
