### ISSUE TITLE
Change round to floor in compendium items

### ISSUE THREAD

**Issue by CatbotTsumi** [Skyl3lazer/giffyglyph-monster-maker-continued#39]
D&D5e rounds down always normally. So i think it makes sense to use floor instead of round in the premade compendium items
![chrome_R3ZD1dRNtf](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/63572588/320460e9-39e5-4dd5-ad87-3fdf977e8fae)

**Comment by Skyl3lazer** [comment]
Confirmed this is as it functions in the pdf
