### ISSUE TITLE
Expanded Conditions Compendium

### ISSUE THREAD

**Issue by CatbotTsumi** [Skyl3lazer/giffyglyph-monster-maker-continued#43]
It would be nice to have the expanded conditions chapter as a compendium for easy reference and linking. I would suggest using default item sheets instead of GGMM items, so that it is familiar to the players who never get to see GGMM sheets.

Bonus points if it integrates with [DFreds Convenient Effects](https://foundryvtt.com/packages/dfreds-convenient-effects) ([Developer Guide](https://github.com/DFreds/dfreds-convenient-effects/wiki/Developer-Guide))

**Comment by Skyl3lazer** [comment]
Added in c5ecb46
