### ISSUE TITLE
Maximum die parameter doesn't properly restrict dice amount

### ISSUE THREAD

**Issue by narayb** [Skyl3lazer/giffyglyph-monster-maker-continued#56]
When setting a fixed Max amt. of dice on the monster sheet it reduces the amount of dice that the sheet shows, but doesn't change the dice amount on attacks when using the formula `[round(damage),damageDie]` for those attacks. Is this intended or am I missing something in the formula?

![image](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/74784772/fa2a8daa-bb23-4e69-938c-15c090d3a39e)

**Comment by Skyl3lazer** [comment]
So this was actually just never implemented apparently. Fixed on dev with 76cceafe

**Comment by narayb** [comment]
Amazing! Thanks for the quick fix!
