### ISSUE TITLE
Trait/Ability Description edit icon disappears upon clicking, unable to edit.

### ISSUE THREAD

**Issue by eldritchkermit** [Skyl3lazer/giffyglyph-monster-maker-continued#58]
When I click the edit icon (circled in red in the first screencap), it simply disappears and leaves the Description space blank (second Screencap).

![Giffyglyph issue screencap1](https://github.com/user-attachments/assets/a0c9936a-718e-4e1f-a9b9-dc427ae1956f)

![Giffyglyph issue screencap2](https://github.com/user-attachments/assets/ad189c21-73d7-42c6-9187-941ae360acc1)

**Comment by eldritchkermit** [comment]
My bad, I apparently had the wrong version of the module installed.

**Comment by Skyl3lazer** [comment]
Let me know if you encounter any issues!
