### ISSUE TITLE
"Cannot read properties of undefined (reading 'wis') [Detected 1 package: system:dnd5e]" when creating new monster

### ISSUE THREAD

**Issue by McBrightside** [Skyl3lazer/giffyglyph-monster-maker-continued#6]
When I click 'create a scaling monster' I get the following error. 
![image](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/6549371/76688dfb-c822-4d25-9dc1-2604da8cb172)

Additionally, when I attempt to convert an existing monster I receive this notification.
![image](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/6549371/869574c7-e763-4926-948a-277813f89154)

Here are my Forge and module versions.
![image](https://github.com/Skyl3lazer/giffyglyph-monster-maker-continued/assets/6549371/3e124fd1-a68c-49ad-bb1a-97e9fb45d52e)

Thank you for continuing development for this module!

**Comment by Skyl3lazer** [comment]
Are you able to get the error from the developer log (f12) with forge?

**Comment by Skyl3lazer** [comment]
@McBrightside Are you able to provide this detail?

**Comment by Skyl3lazer** [comment]
Closed unless user can provide more info. Possibly already fixed in other patches.
